### PR TITLE
Fix broken Visual Studio build

### PR DESCRIPTION
**Pull request by Maghoumi**
Hello Gabriel, it's me again : )
When I tried building with VS 2015, I noticed there were a couple of minor issues preventing the build. This PR fixes those issues. I can confirm that the project builds fine under VS 2015 and the example works. Similar to before, the tests don't build under VS.

Hope this helps.
Cheers

### CODE REVIEW

**Comment by gabyx** [comment]
Thanks, could you explain why you commented out in EstimateDiameter. ??
This might break somethings unexpectedly

**Comment by Maghoumi** [comment]
No problem.
In one of your previous commits, you have commented out the implementation of the function `_CountPointsInSpheres`. Also the code that's calling that function is inside an `if(0)` statement, and therefore is never called. My guess is that GCC completely ignores `if(0)` statement and does not even compile them. On VS however, the compiler was looking for the implementation of   `_CountPointsInSpheres`. Since it couldn't find it, it was generating linker errors. I commented that line out and now everything compiles. To be honest, I don't know what the function of `_CountPointsInSpheres` is and why you've commented it out! : )

**Comment by gabyx** [comment]
ah perfect! will look through it. thanks for the contribution! 

Von meinem iPhone gesendet

**Review by gabyx — CHANGES_REQUESTED** [review]
Thanks for the changes: why do you need the include "time.h" in RandomGenerators.hpp. Please provide some compile output, the time.h is probably needed somewhere else.

Thanks a lot!

**Comment by Maghoumi** [comment]
The function `time` called in that file required that header. I think the MSVC include chain did not include a header in which `time` was included. Adding `#include<time.h>` solved those issues.

**Comment by gabyx** [comment]
Sorry, of course, I searched for it, but did not find it sorry, :-)

**Review by gabyx — APPROVED** [review]

**Pull request merged**
